server:
  port: 18080

spring:
  application:
    name: nacos-discovery-example

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        enabled: true
        username: naocs
        password: nacos